log_dir: ${name}/
task: Evaluate
status: train

name: Evaluate
tensorboard: false

# GENERAL
seed: 123
workers: 4
gpu_ids: 0

# LOG ROOT
log_root: /media/data/Xiang/logs/Mul-AE
print_freq: 10

# MODEL
arch: 
  _target_: srcs.model.vit_model.create_model
  model_name: vit_base_patch16
  finetune:  D:/Work/Xiang/logs/Mul-AE/Experiment/DISFA/2022-03-19/11-05-22/fold3/models/checkpoint-epoch4.pth # ViT 
  num_classes: 8
  drop_path: 0.1

channel_mixing: false

#DATASET
# data_name: BP4D
# csv_root: /media/data/Xiang/csv/BP4D/Huiyuan/train_test_depth
# texture_root: /media/data/Xiang/${data_name}/Texture_crop
# depth_root: /media/data/Xiang/${data_name}/DepthCrop

data_name: DISFA
csv_root: E:/csv/Disfa/Huiyuan
texture_root: E:/Data/Texture_crop/${data_name}

modalities: ['texture']
training: false
batch_size: 128
fold: 'fold3'

# TRANSFORM
input_size: 224

# METRIC
metrics:
  - _target_: srcs.model.metric.F1
# CRITERIONS
criterions:
  - _target_: srcs.model.loss.bce_logit_loss
    train: false


defaults:
  - hydra/job_logging : custom
  - hydra/run/dir: job_timestamp

